// routes/SidebarRoutes.js
import { ChatBubbleOvalLeftIcon } from "@heroicons/react/24/outline";
import {
  User,
  Mail,
  Share2,
  Info,
  Landmark,
  Monitor,
  Newspaper,
  FileText,
  Clock,
  BarChart2,
  FilePlus2,
  CalendarDays,
  Waves,
  HelpCircle,
  MessageSquare,
  Layout,
  Radio,
  Settings,
  Volleyball,
} from "lucide-react";

export const PortalSidebarRoutes = [
  { label: "User Details", path: "portal/user-details", icon: User },
  // { label: "Email Preference", path: "portal/email-preference", icon: Mail },
  // { label: "Committees", path: "portal/committees", icon: Share2 },
  // { label: "Access Information", path: "portal/access-information", icon: Info },
  // { label: "HOA Board", path: "portal/hoa-board", icon: Landmark },
  // { label: "Member Directory", path: "portal/member-directory", icon: Monitor },
  // { label: "Newsletter", path: "portal/newsletter", icon: Newspaper },
  // { label: "Common Documents", path: "portal/common-documents", icon: FileText },
  // { label: "Monthly Meeting Minutes", path: "portal/monthly-meeting-minutes", icon: Clock },
  // { label: "Financial Documents", path: "portal/financial-documents", icon: BarChart2 },
  // { label: "Board Documents", path: "portal/board-documents", icon: FilePlus2 },
  // { label: "Calenders & Reservation", path: "portal/calender-reservations", icon: CalendarDays },
  // { label: "Pools", path: "portal/pools", icon: Waves },
  // { label: "Stingrays Swim Team", path: "portal/stingrays-swim-team", icon: CalendarDays },
  // { label: "Tennis", path: "portal/tennis", icon: Volleyball },
  // { label: "Help", path: "portal/help", icon: HelpCircle },
  // { label: "Frequently Asked Questions", path: "portal/faqs", icon: MessageSquare },
  // { label: "Pages", path: "portal/pages", icon: Layout },
  // { label: "Mass Email Communication", path: "portal/mass-email", icon: Radio },
  { label: "Settings", path: "portal/settings", icon: Settings },
];
